export const DEFAULT_PRESS_SERVICES = [
  "Photocopy (black & white)",
  "Photocopy (colour)",
  "Digital print (A4 colour)",
  "Digital print (A4 black & white)",
  "Business cards",
  "Flyers / handbills",
  "Brochures",
  "Letterheads",
  "Posters",
  "Banners",
  "Roll-up banner",
  "Flex / outdoor signage",
  "Stickers & labels",
  "ID cards",
  "Certificates",
  "Invitation / wedding cards",
  "T-shirt printing",
  "Cap printing",
  "Mug printing",
  "Canvas print",
  "Photo print",
  "Lamination",
  "Spiral / comb binding",
  "Cutting & trimming",
  "Scanning",
  "Graphic design / typesetting",
  "Receipt / invoice books",
  "Vehicle branding",
] as const;
