export const DEFAULT_PRINT_MATERIALS: {
  category: string;
  sku: string;
  name: string;
  description: string;
}[] = [
  {
    category: "Paper & substrates",
    sku: "PAP-A4-80",
    name: "A4 Bond Paper 80gsm (ream)",
    description: "Everyday copy and digital print paper.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-A4-100",
    name: "A4 Bond Paper 100gsm (ream)",
    description: "Heavier letterhead and document paper.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-A3-80",
    name: "A3 Bond Paper 80gsm (ream)",
    description: "A3 copy and poster paper.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-ART-128",
    name: "Art Paper 128gsm",
    description: "Gloss/matt paper for flyers and brochures.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-ART-150",
    name: "Art Paper 150gsm",
    description: "Flyers, posters, and brochures.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-ART-200",
    name: "Art Paper 200gsm",
    description: "Thick flyer and cover stock.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-CARD-250",
    name: "Art Card 250gsm",
    description: "Cards, covers, and folders.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-CARD-300",
    name: "Business Card Stock 300gsm",
    description: "Matte or gloss card for business cards.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-NCR",
    name: "NCR / Carbonless Paper",
    description: "Invoice and receipt books.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-PHOTO",
    name: "Photo Paper",
    description: "Gloss photo prints.",
  },
  {
    category: "Paper & substrates",
    sku: "PAP-STK-A4",
    name: "A4 Sticker Paper",
    description: "Label and sticker sheets.",
  },
  {
    category: "Large format",
    sku: "LF-VINYL",
    name: "Adhesive Vinyl Roll",
    description: "Stickers, vehicle, and signage vinyl.",
  },
  {
    category: "Large format",
    sku: "LF-FLEX",
    name: "Flex Banner",
    description: "Outdoor flex for banners and billboards.",
  },
  {
    category: "Large format",
    sku: "LF-FABRIC",
    name: "Banner Fabric",
    description: "Indoor/outdoor fabric banners.",
  },
  {
    category: "Large format",
    sku: "LF-MESH",
    name: "Mesh Banner",
    description: "Wind-through outdoor mesh.",
  },
  {
    category: "Large format",
    sku: "LF-CANVAS",
    name: "Canvas Roll",
    description: "Canvas prints and frames.",
  },
  {
    category: "Large format",
    sku: "LF-ROLLUP",
    name: "Roll-up Banner Media",
    description: "Media for roll-up stands.",
  },
  {
    category: "Large format",
    sku: "LF-OWV",
    name: "One-way Vision Vinyl",
    description: "Window and vehicle perforated vinyl.",
  },
  {
    category: "Large format",
    sku: "LF-CLEAR",
    name: "Clear Vinyl",
    description: "Transparent sticker and glass graphics.",
  },
  {
    category: "Large format",
    sku: "LF-FOREX",
    name: "PVC / Forex Board",
    description: "Rigid sign boards.",
  },
  {
    category: "Large format",
    sku: "LF-FOAM",
    name: "Foam Board",
    description: "Indoor mounted prints.",
  },
  {
    category: "Ink & toner",
    sku: "INK-CMYK",
    name: "CMYK Ink Set",
    description: "Digital press colour ink.",
  },
  {
    category: "Ink & toner",
    sku: "INK-BLK-TNR",
    name: "Black Toner",
    description: "Copier / laser black toner.",
  },
  {
    category: "Ink & toner",
    sku: "INK-CLR-TNR",
    name: "Colour Toner",
    description: "Copier / laser colour toner.",
  },
  {
    category: "Ink & toner",
    sku: "INK-ECO",
    name: "Eco-solvent Ink",
    description: "Large format printer ink.",
  },
  {
    category: "Ink & toner",
    sku: "INK-DTG",
    name: "DTG Ink",
    description: "Direct-to-garment printing ink.",
  },
  {
    category: "Ink & toner",
    sku: "INK-SCREEN",
    name: "Screen Print Ink",
    description: "Plastisol / water-based screen ink.",
  },
  {
    category: "Finishing",
    sku: "FIN-LAM-A4",
    name: "A4 Laminating Pouches",
    description: "ID, certificates, and menus.",
  },
  {
    category: "Finishing",
    sku: "FIN-LAM-A3",
    name: "A3 Laminating Pouches",
    description: "Larger certificates and menus.",
  },
  {
    category: "Finishing",
    sku: "FIN-LAM-ROLL",
    name: "Lamination Roll",
    description: "Gloss or matt roll lamination.",
  },
  {
    category: "Finishing",
    sku: "FIN-SPIRAL",
    name: "Spiral Binding Coils",
    description: "Notebook and document binding.",
  },
  {
    category: "Finishing",
    sku: "FIN-COMB",
    name: "Comb Binding Spines",
    description: "Comb-bound documents.",
  },
  {
    category: "Finishing",
    sku: "FIN-COVER",
    name: "Binding Covers",
    description: "Front and back covers.",
  },
  {
    category: "Apparel blanks",
    sku: "APP-TEE",
    name: "Blank T-Shirt",
    description: "Cotton blank for print.",
  },
  {
    category: "Apparel blanks",
    sku: "APP-POLO",
    name: "Blank Polo Shirt",
    description: "Polo blank for embroidery or print.",
  },
  {
    category: "Apparel blanks",
    sku: "APP-CAP",
    name: "Blank Cap",
    description: "Cap for embroidery or print.",
  },
  {
    category: "Apparel blanks",
    sku: "APP-MUG",
    name: "Blank Mug",
    description: "Mug for sublimation print.",
  },
];
